version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - echo "Cloning GitHub repository..."
      - git clone https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git
  build:
    commands:
      - echo "Building Lambda functions..."
      - for function_path in ./your_repo_directory/lambda_functions/*; do \
          function_name=$(basename $$function_path); \
          echo "Building $$function_name..."; \
          cd $$function_path && zip -r ../../$$function_name.zip . && cd ../..; \
        done

artifacts:
  files:
    - '*.zip'  # すべてのZIPファイルを出力
