version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - echo "Cloning GitHub repository..."
      - git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git

  build:
    commands:
      - echo "Displaying folder list..."
      - ls -l ${GITHUB_REPO}  # クローン後のフォルダリストを表示
      - mkdir -p /tmp  # /tmpディレクトリを作成
      - echo "Zipping Lambda functions..."
      - |
        for function_path in $(ls -d ${GITHUB_REPO}/*/); do  # ディレクトリごとにループ
          function_name=$(basename "$function_path")
          echo "Zipping $function_name..."
          zip -jr "/tmp/${function_name}.zip" "$function_path"
          aws s3 cp "/tmp/${function_name}.zip" "s3://lambda-kamiguchi/"
        done

artifacts:
  files:
    - '/tmp/*.zip'  # /tmpディレクトリ内の全てのZIPファイルをアーティファクトとして出力
  discard-paths: no
